name: Lighthouse CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 18.17

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn run build
        env:
          SHOPIFY_STORE_DOMAIN: ${{ secrets.SHOPIFY_STORE_DOMAIN }}
          SHOPIFY_STOREFRONT_ACCESS_TOKEN: ${{ secrets.SHOPIFY_STOREFRONT_ACCESS_TOKEN }}

      - name: Run Lighthouse
        id: lighthouse
        uses: treosh/lighthouse-ci-action@10.1.0
        with:
          urls: |
            https://commerce-git-${{ github.head_ref || github.ref_name }}-kasperbirch1.vercel.app/
          uploadArtifacts: true
          configPath: './lighthouserc.json'
